name: Run yfinance Stock Data Collector

on:
  workflow_dispatch:  # 使用 workflow_dispatch 触发方式
  schedule:
    - cron: '50 17 * * *'  # 每天北京时间下午5点50分执行一次

jobs:
  collect_stock_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # 指定Python版本为3.11

    - name: Install dependencies
      run: pip install yfinance pandas openpyxl  # 安装所需的Python依赖项

    - name: Run yfinance Stock Data Collector
      run: python 获取行情数据yu自定义2.py  # 运行你的Python脚本
      working-directory: ./data  # 指定工作目录为./data
